# Generated by Django 6.0.3 on 2026-05-04 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=50, unique=True)),
                ('fecha_produccion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad_inicial', models.IntegerField()),
                ('cantidad_actual', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza_ave', models.CharField(max_length=100)),
                ('mortalidad_acumulada', models.IntegerField(default=0)),
                ('observaciones', models.TextField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='produccion.lote')),
            ],
        ),
    ]
