# Generated by Django 6.0.3 on 2026-05-04 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_perdida', models.IntegerField()),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mermas', to='produccion.lote')),
            ],
        ),
    ]
