# Generated by Django 6.0.3 on 2026-05-04 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('unidad_medida', models.CharField(max_length=10)),
                ('estado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Agricola',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='productos.producto')),
                ('variedad', models.CharField(max_length=100)),
                ('estado_madurez', models.CharField(max_length=50)),
                ('tratamiento', models.TextField()),
                ('humedad_optima', models.CharField(max_length=50)),
            ],
            bases=('productos.producto',),
        ),
        migrations.CreateModel(
            name='Detalle_Avicola',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='productos.producto')),
                ('talla', models.CharField(max_length=20)),
                ('color_huevo', models.CharField(max_length=30)),
                ('tipo_empaque', models.CharField(max_length=50)),
                ('categoria_calidad', models.CharField(max_length=50)),
                ('limpieza', models.BooleanField(default=True)),
            ],
            bases=('productos.producto',),
        ),
    ]
